# Generated by Django 6.0.6 on 2026-06-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('single', 'Single Room'), ('apartment', 'Apartment'), ('house', 'House')], default='flat', max_length=20),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
