# Generated by Django 6.0.6 on 2026-06-17 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_room_type_alter_room_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('flat', 'Flat'), ('single', 'Single Room'), ('2 rooms', '2 Rooms'), ('apartment', 'Apartment'), ('house', 'House'), ('hostel', 'Hostel'), ('office space', 'Office Spaces'), ('shutter', 'Shutter')], default='flat', max_length=20),
        ),
    ]
