# Generated by Django 6.0.6 on 2026-06-18 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='savedroom',
            options={'ordering': ['-saved_at']},
        ),
        migrations.AddField(
            model_name='room',
            name='area',
            field=models.CharField(blank=True, help_text='Area / Tole', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='bill_electricity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='bill_internet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='bill_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_bike_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_cctv',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_drinking_water',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_laundry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_security_guard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='has_water_24_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='pet_allowed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='security_deposit',
            field=models.PositiveIntegerField(default=0, help_text='Security deposit in NPR'),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('rented', 'Rented')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='ward_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='city',
            field=models.CharField(help_text='City or VDC', max_length=100),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(help_text='Minimum 100 characters'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Monthly rent in NPR', max_digits=10),
        ),
        migrations.AlterField(
            model_name='savedroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='savedroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('province', 'name')},
        ),
        migrations.CreateModel(
            name='LandlordProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_landlord', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='rooms.room')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
