# Generated by Django 6.0.6 on 2026-06-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_verified',
        ),
        migrations.AddField(
            model_name='room',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
