# Generated by Django 6.0.6 on 2026-06-24 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_profile_delete_landlordprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_front', models.ImageField(upload_to='documents/')),
                ('citizenship_back', models.ImageField(upload_to='documents/')),
                ('lalpurja', models.ImageField(upload_to='documents/')),
                ('selfie', models.ImageField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rooms.room')),
            ],
        ),
    ]
