# Generated by Django 6.0.6 on 2026-06-24 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_remove_room_is_verified_room_rejection_reason_and_more'),
        ('rooms', '0008_verificationdocument_is_verified_and_more'),
    ]

    operations = [
    ]
