# Generated by Django 6.0.6 on 2026-06-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_merge_20260624_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('rented', 'Rented')], default='draft', max_length=10),
        ),
    ]
