# Generated by Django 6.0.6 on 2026-07-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_userpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('rented', 'Rented')], default='draft', max_length=10),
        ),
    ]
