# Generated by Django 6.0.6 on 2026-07-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0013_alter_room_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='furnished',
        ),
        migrations.AddField(
            model_name='room',
            name='furnished_status',
            field=models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('semi', 'Semi-Furnished')], default='unfurnished', max_length=15),
        ),
        migrations.AddField(
            model_name='room',
            name='has_kitchen',
            field=models.BooleanField(default=False),
        ),
    ]
