# Generated by Django 6.0.6 on 2026-07-13 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0015_advertisement'),
        ('rooms', '0015_profile_is_verified_emailotp'),
    ]

    operations = [
    ]
