# Generated by Django 6.0.6 on 2026-07-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0016_merge_20260713_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedroom',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
