# Generated by Django 6.0.6 on 2026-07-26 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0017_savedroom_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
