# Generated by Django 6.0.6 on 2026-07-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ads/')),
                ('redirect_url', models.URLField(blank=True)),
                ('placement', models.CharField(choices=[('homepage_banner', 'Homepage Banner'), ('sidebar', 'Sidebar'), ('listing_page', 'Listing Page')], default='homepage_banner', max_length=30)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
